CXX =  Driver.cpp
CXX += Menu.hpp
CXX += Menu.cpp
CXX += LinearSearch.hpp
CXX += LinearSearch.cpp
CXX += BubbleSort.hpp
CXX += BubbleSort.cpp
CXX += BinarySearch.hpp
CXX += BinarySearch.cpp

default:
	g++ -std=c++0x ${CXX} -o prog
	
clean:
	rm prog
