CXX =  Driver.cpp
CXX += ER.hpp
CXX += ER.cpp
CXX += FrontDoor.hpp
CXX += FrontDoor.cpp
CXX += Hospital.hpp
CXX += Hospital.cpp
CXX += IP.hpp
CXX += IP.cpp
CXX += Lab.hpp
CXX += Lab.cpp
CXX += Library.hpp
CXX += Library.cpp
CXX += LowerHall.hpp
CXX += LowerHall.cpp
CXX += UpperHall.hpp
CXX += UpperHall.cpp

default:
	g++ -std=c++0x ${CXX} -o prog
	
clean:
	rm prog
