CXX =  Main.cpp
CXX += Game.hpp
CXX += Game.cpp
CXX += Creature.hpp
CXX += Creature.cpp
CXX += Vampire.hpp
CXX += Vampire.cpp
CXX += Barbarian.hpp
CXX += Barbarian.cpp
CXX += Bluemen.hpp
CXX += Bluemen.cpp
CXX += Medusa.hpp
CXX += Medusa.cpp
CXX += Potter.hpp
CXX += Potter.cpp

default:
	g++ -std=c++0x ${CXX} -o prog
	
clean:
	rm prog
