CXX =  Menu.hpp
CXX += Menu.cpp
CXX += CalculateSum.hpp
CXX += CalculateSum.cpp
CXX += ReverseString.hpp
CXX += ReverseString.cpp
CXX += TriangularNumber.hpp
CXX += TriangularNumber.cpp

default:
	g++ -std=c++0x ${CXX} -o prog
	
clean:
	rm prog
